---
- hosts: web
  sudo: yes

  vars: 
    http_port: 80
    doc_root: "/var/www/html"
    name: Jenkins-CI_CD
  
  tasks:
  - name: Install Apache Packages on Debian
    apt: name=apache2 state=present
    when: ansible_os_family == "Debian"


  - name: Start Apache Service on Debian
    service: name=apache2 state=started
    when: ansible_os_family == "Debian"


  - name: Install Apache Packages on CentOS
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"


  - name: Start Apache Service on CentOS
    service: name=httpd state=started
    when: ansible_os_family == "RedHat"


  - debug: msg="This is {{name}} what you supplied"


  - name: Deploy Custom Apache Config.
    template: src=templates/apache2.j2 dest=/etc/apache2/apache2.conf
    notify:
      - Restart Apache

  - name: Create Site Location
    file: path={{doc_root}} state=directory

  - name: Download Super Mario Background Image. 
    get_url: url="http://www.mariomayhem.com/downloads/wallpapers/2/nsmb_wp2_1024.jpg" dest={{doc_root}}/mario.jpg mode=0755

  - name: Deploy Index File
    copy: src=templates/index.html dest={{doc_root}}/index.html

  
  - name: Deploy Info. File
    template: src=templates/info.j2 dest={{doc_root}}/info.html

  handlers: 
  - name: Restart Apache
    service: name=apache2 state=restarted




